export const ADD_USER = 'ADD_USER';

export const GET_TOKEN_SUCCESS = 'GET_TOKEN_SUCCESS';

export const SEND_SCORE = 'SEND_SCORE';

export const SEND_ASSERTIONS = 'SEND_ASSERTIONS';

export const SEND_PICTURE_GRAVATAR = 'SEND_PICTURE_GRAVATAR';
